# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj0 = bld.create_ns3_program('keysight-example', ['keysight', 'csma', 'internet', 'applications', 'internet-apps'])
    obj0.source=['srt-fattree.cc']
    #obj1 = bld.create_ns3_program('keysight-test', ['keysight', 'csma', 'internet', 'applications', 'internet-apps'])
    #obj1.source = ['keysight-test.cc']
